apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max
spec:
  limits:
  - default:
      cpu: 300m
      memory: 128Mi
    defaultRequest:
      cpu: 300m
      memory: 128Mi
    max:
      cpu: 800m
      memory: 1Gi
    min:
      cpu: 200m
      memory: 70Mi
    type: Container
