---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-monitor-role
rules:
  - apiGroups: [""]
    resources: ["events", "nodes", "pods", "pods/log", "deployments", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get","list","watch"]