---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-monitor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-monitor-role
subjects:
  - kind: ServiceAccount
    name: kube-monitor-account
