{
 "title": "Kubernetes Track Resource Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Pods Wastage Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc((sum(label_replace(kube_pod_container_resource_requests{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\", resource=\"memory\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)) - (sum(label_replace(container_memory_working_set_bytes{container=\"\", namespace=~\"kube-monitor|echo\"}, \"podName\",  \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName))))"
    }
   ]
  },
  {
   "title": "Pods Wastage cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc((sum(label_replace(kube_pod_container_resource_requests{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\", resource=\"cpu\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)) - (sum(label_replace(rate(container_cpu_usage_seconds_total{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\"}[1m]), \"podName\",  \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName))))"
    }
   ]
  },
  { "title": "Pod Requested Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pod Requested Resource Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(label_replace(kube_pod_container_resource_requests{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\", resource=\"memory\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)))"
    }
   ]
  },
  {
   "title": "POD Requested Resource CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(label_replace(kube_pod_container_resource_requests{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\", resource=\"cpu\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)))"
    }
   ]
  },
  { "title": "POD resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top POD Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(label_replace(container_memory_working_set_bytes{container=\"\", namespace=~\"kube-monitor|echo\"}, \"podName\",  \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)))"
    }
   ]
  },
  {
   "title": "Top POD CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(label_replace(rate(container_cpu_usage_seconds_total{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\"}[1m]), \"podName\",  \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\")) by (namespace, podName)))"
    }
   ]
  },
  {
   "title": "Namespace resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, sort_desc(sum(avg_over_time(container_memory_working_set_bytes{container=\"\", namespace=~\"kube-monitor|echo\"}[1m])) by (namespace)))"
      }
     ]
    },
    {
     "title": "Namespace CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "yaxes": [
      { "format": "cpu" }
     ],
     "targets": [
      {
       "expr": "topk(5, sort_desc(sum(rate(container_cpu_usage_seconds_total{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo\"}[1m])) by (namespace)))",
       "legendFormat": "{{ namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Restart Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restarts Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(sort_desc(label_replace(kube_pod_container_status_restarts_total{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo|kube-system\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\"))) by (namespace, podName))"
      }
     ]
    },
    {
     "title": "Pod Restart Reasons",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg(sort_desc(label_replace(kube_pod_container_status_waiting_reason{app_kubernetes_io_name=\"\", namespace=~\"kube-monitor|echo|kube-system\"}, \"podName\", \"$1$3\", \"pod\", \"(.*)(-.{9,10}-.{5})|(.*)\"))) by (namespace, podName, reason))"
      }
     ]
    }
   ]
  },
  {
   "title": "PV/PVC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "PV Top 5 Volume Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, sort_desc(max(kube_persistentvolume_capacity_bytes) by (persistentvolume)))"
      }
     ]
    }
   ]
  }
 ]
}