apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "events"]
  verbs: ["get", "watch", "list"]
